{
 "title": "Kafka producer metric",
 "description": "Dashboard for Kafka producer metrics",
 "tags": [ "0.0.1" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "clientId", "label": "client-id", "query": "label_values(client_id)" }
  ]
 },
 "panels": [
  { "title": "Kafka Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Buff使用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "((producer_metrics_buffer_total_bytes{client_id=~\"$clientId\"} - producer_metrics_buffer_available_bytes{client_id=~\"$clientId\"})/producer_metrics_buffer_total_bytes{client_id=~\"$clientId\"})",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "最大I/O线程耗时占比",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(producer_metrics_io_ratio{client_id=~\"$clientId\"})",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "请求延迟",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "(producer_metrics_request_latency_max{client_id=~\"$clientId\"})",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "最大request大小",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(producer_metrics_request_size_max{client_id=~\"$clientId\"})",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "最大Batch大小",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "(producer_metrics_batch_size_max{client_id=~\"$clientId\"})",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "队列时间",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "(producer_metrics_record_queue_time_max{client_id=~\"$clientId\"})",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "平均请求延迟（毫秒）",
   "type": "graph",
   "description": "Kafka Broker Pods Memory Usage",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_request_latency_avg{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "record batches在发送缓冲区中花费的平均时间（毫秒）",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_record_queue_time_avg{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "当前等待响应的in fight的请求数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_requests_in_flight{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "平均压缩率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(producer_metrics_compression_rate_avg{client_id=~\"$clientId\"})",
     "legendFormat": "压缩率"
    }
   ]
  },
  {
   "title": "当前活动连接数",
   "type": "graph",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_connection_count_count{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "record batches在发送缓冲区中花费的最长时间（毫秒）",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_record_queue_time_max{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "每次select调用的I/O平均时间长度（微秒）",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_io_time_ns_avg{client_id=~\"$clientId\"}/1000",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "当前producer元数据使用的时间",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_metadata_age{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "平均每秒因缓冲区耗尽而丢弃的记录发送数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_buffer_exhausted_rate{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "io_ratio",
   "type": "graph",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_io_ratio{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "发送的任何请求的最大大小",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_request_size_max{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "平均每秒重试数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_record_retry_rate{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "user processing time",
   "type": "graph",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1- producer_metrics_io_wait_ratio{client_id=~\"$clientId\"} - producer_metrics_io_ratio{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "io_wait_ratio",
   "type": "graph",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_io_wait_ratio{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "平均record的大小",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_record_size_avg{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "平均batch的大小",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_batch_size_avg{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "outgoing_byte_rate",
   "type": "graph",
   "description": "The average number of outgoing bytes sent per second to all servers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_outgoing_byte_rate{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "每秒关闭的连接数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_connection_close_rate{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "平均每秒发送导致错误的记录数",
   "type": "graph",
   "description": "The average number of requests sent per second.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_record_error_rate{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "平均request的大小",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_request_size_avg{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "每个请求的平均记录数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_records_per_request_avg{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "每秒接收的响应数",
   "type": "graph",
   "description": "Responses received by Producer from Broker per second.\nDepending on your configuration, “received” could mean a couple of things:\nThe message was received, but not committed (request.required.acks == 0)\nThe leader has written the message to disk (request.required.acks == 1)\nThe leader has received confirmation from all replicas that the data has been written to disk (request.required.acks == -1)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_response_rate{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "请求被broker限制的平均时间（毫秒）",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_produce_throttle_time_avg{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "平均每秒发送的Producer请求数",
   "type": "graph",
   "description": "The average number of requests sent per second.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_request_rate{client_id=~\"$clientId\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  }
 ]
}